
server.port=8080
spring.application.name=gateway_escuela_modelo


# Configuración de Eureka Client 
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Definición de rutas para los microservicios
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://productservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[0].filters[1]=PrefixPath=/products-api

spring.cloud.gateway.server.webflux.routes[1].id=coupon-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://couponservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/coupons/**